# file: C:\Users\abel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\urllib3\connectionpool.py
# hypothesis_version: 6.131.10

[303, '/', '443', '80', 'Connection aborted.', 'GET', 'No host specified.', 'Pool is closed.', 'Redirecting %s -> %s', 'Retry-After', 'Retry: %s', '[', ']', 'errno', 'http', 'https', 'proxy', 'proxy_config', 'socket_options']